"""지식베이스 시드 데이터. 초기 RAG 참고 자료."""

SEED_CHUNKS = [
    # ── 공통 intro ──
    {
        "role_key": "공통",
        "company_name": None,
        "category": "intro",
        "question": "1분 자기소개를 부탁드립니다.",
        "ideal_answer": "지원 직무와 연결된 핵심 경험 2가지 + 지원 동기를 30초~1분 내에 정리. 수치 1개 포함. 끝에 '잘 부탁드립니다' 마무리.",
        "keywords": ["자기소개", "소개", "본인"],
        "quality_score": 1.0,
    },
    {
        "role_key": "공통",
        "company_name": None,
        "category": "intro",
        "question": "지원 동기가 무엇인가요?",
        "ideal_answer": "회사 비전/사업 방향과 본인 커리어 방향의 교차점 제시. 단순 '성장하고 싶다'보다 '이 회사의 X 서비스에서 Y 문제를 해결하는 데 기여하고 싶다' 수준.",
        "keywords": ["지원 동기", "왜 지원"],
        "quality_score": 1.0,
    },
    {
        "role_key": "공통",
        "company_name": None,
        "category": "situation",
        "question": "실패한 경험과 그로부터 배운 점을 말씀해 주세요.",
        "ideal_answer": "실패 상황 구체화(S/T) → 본인 역할과 판단 오류 인정(A) → 이후 행동 변화와 성과 개선(R). 자책보다 학습과 성장에 방점.",
        "keywords": ["실패", "실수", "배움"],
        "quality_score": 1.0,
    },
    # ── 백엔드 개발자 ──
    {
        "role_key": "백엔드 개발자",
        "company_name": None,
        "category": "technical",
        "question": "트래픽이 급증했을 때 대응한 경험을 말씀해 주세요.",
        "ideal_answer": "S: 서비스 배경/트래픽 규모 → T: 병목 지점 → A: 스케일 아웃/캐싱/DB 인덱스/쿼리 최적화 등 구체 조치 → R: 응답 시간 X% 개선, 에러율 Y% 감소. 수치 필수.",
        "keywords": ["트래픽", "성능", "스케일", "캐싱", "DB"],
        "quality_score": 1.0,
    },
    {
        "role_key": "백엔드 개발자",
        "company_name": None,
        "category": "technical",
        "question": "RESTful API 설계 시 중요하게 고려하는 원칙은 무엇인가요?",
        "ideal_answer": "리소스 중심 URI, HTTP 메서드 의미 준수, 상태 코드 정확성, 버저닝 전략, 페이지네이션, 인증/인가 분리. 실무 예시 포함.",
        "keywords": ["REST", "API", "설계", "HTTP"],
        "quality_score": 1.0,
    },
    {
        "role_key": "백엔드 개발자",
        "company_name": None,
        "category": "competency",
        "question": "가장 어려웠던 기술 부채를 해결한 경험을 말씀해 주세요.",
        "ideal_answer": "부채의 구체적 원인 + 비즈니스 영향 → 해결 접근법(리팩토링 vs 재설계) → 팀 설득 과정 → 결과(배포 빈도/버그율 수치). 단계적 접근 강조.",
        "keywords": ["기술 부채", "레거시", "리팩토링"],
        "quality_score": 1.0,
    },
    {
        "role_key": "백엔드 개발자",
        "company_name": None,
        "category": "technical",
        "question": "데이터베이스 인덱스 설계 경험을 설명해 주세요.",
        "ideal_answer": "쿼리 패턴 분석(EXPLAIN) → 복합 인덱스 설계 기준 → 커버링 인덱스 활용 → 인덱스 과다/불필요 인덱스 제거 → 쿼리 성능 개선 수치.",
        "keywords": ["인덱스", "DB", "쿼리", "성능"],
        "quality_score": 1.0,
    },
    # ── 프론트엔드 개발자 ──
    {
        "role_key": "프론트엔드 개발자",
        "company_name": None,
        "category": "technical",
        "question": "웹 성능 최적화를 위해 어떤 방법을 사용하셨나요?",
        "ideal_answer": "번들 사이즈 분석(webpack-bundle-analyzer) → 코드 스플리팅 → lazy loading → 이미지 최적화(WebP/AVIF) → 캐시 전략(Cache-Control) → CWV(LCP/INP/CLS) 수치 개선 사례.",
        "keywords": ["성능", "최적화", "번들", "Core Web Vitals"],
        "quality_score": 1.0,
    },
    {
        "role_key": "프론트엔드 개발자",
        "company_name": None,
        "category": "technical",
        "question": "상태 관리 라이브러리 선택 기준을 어떻게 정하시나요?",
        "ideal_answer": "서버 상태(TanStack Query/SWR)와 클라이언트 상태(Zustand/Jotai) 분리. 규모·팀 숙련도·번들 크기 고려. URL 상태 활용. 전역 상태 최소화 원칙.",
        "keywords": ["상태 관리", "Redux", "Zustand", "React"],
        "quality_score": 1.0,
    },
    {
        "role_key": "프론트엔드 개발자",
        "company_name": None,
        "category": "competency",
        "question": "접근성(Accessibility)을 고려한 개발 경험이 있으신가요?",
        "ideal_answer": "WCAG 2.1 기준 → 시맨틱 HTML → ARIA 레이블 → 키보드 내비게이션 → 스크린리더 테스트(NVDA/VoiceOver) → 색 대비 검사 도구 활용 → 개선 사례.",
        "keywords": ["접근성", "a11y", "WCAG", "스크린리더"],
        "quality_score": 1.0,
    },
    # ── PM(프로덕트 매니저) ──
    {
        "role_key": "PM(프로덕트 매니저)",
        "company_name": None,
        "category": "competency",
        "question": "데이터 기반으로 제품 방향을 결정한 경험을 말씀해 주세요.",
        "ideal_answer": "지표 설정(retention/DAU/NPS) → 데이터 분석으로 가설 수립 → A/B 테스트 또는 사용자 인터뷰 → 우선순위 결정(RICE/Impact-Effort) → 결과 수치. 데이터와 정성 결합 강조.",
        "keywords": ["데이터", "지표", "A/B", "프로덕트"],
        "quality_score": 1.0,
    },
    {
        "role_key": "PM(프로덕트 매니저)",
        "company_name": None,
        "category": "situation",
        "question": "개발팀과 의견 충돌이 있었을 때 어떻게 해결했나요?",
        "ideal_answer": "충돌 배경(기술 부채 vs 신기능) → 개발자 관점 경청 → 공통 목표(사용자 가치) 재확인 → 트레이드오프 문서화 → 합의 도출. 감정이 아닌 데이터/원칙 중심 해결.",
        "keywords": ["협업", "갈등", "개발팀", "커뮤니케이션"],
        "quality_score": 1.0,
    },
    {
        "role_key": "PM(프로덕트 매니저)",
        "company_name": None,
        "category": "competency",
        "question": "출시한 기능이 기대와 다른 결과를 냈을 때 어떻게 대응했나요?",
        "ideal_answer": "실패 지표 확인(DAU/전환율 등) → 원인 가설 수립(유저 리서치/로그 분석) → 빠른 롤백 또는 개선 결정 기준 → 팀 레트로스펙티브 → 재실험 설계.",
        "keywords": ["실패", "지표", "롤백", "개선"],
        "quality_score": 1.0,
    },
    # ── 퍼포먼스 마케터 ──
    {
        "role_key": "퍼포먼스 마케터",
        "company_name": None,
        "category": "technical",
        "question": "ROAS를 개선하기 위해 어떤 접근을 하셨나요?",
        "ideal_answer": "캠페인 구조 분석(소재/타겟/입찰) → 저성과 캠페인 예산 이동 → 소재 A/B 테스트 → 오디언스 최적화(리타겟팅/유사 타겟) → 랜딩 페이지 CRO → 결과(ROAS X→Y, CPA Z% 감소).",
        "keywords": ["ROAS", "광고", "퍼포먼스", "전환"],
        "quality_score": 1.0,
    },
    {
        "role_key": "퍼포먼스 마케터",
        "company_name": None,
        "category": "competency",
        "question": "예산이 제한된 상황에서 성과를 낸 경험을 말씀해 주세요.",
        "ideal_answer": "채널 믹스 분석(CAC/ROAS) → 고효율 채널 집중 → 오가닉(SEO/콘텐츠) 병행 → 세그먼트별 타겟 최적화 → 결과(예산 X% 감소, 전환 Y% 유지).",
        "keywords": ["예산", "효율", "채널", "CAC"],
        "quality_score": 1.0,
    },
    # ── 데이터 분석가 ──
    {
        "role_key": "데이터 분석가",
        "company_name": None,
        "category": "technical",
        "question": "분석 결과를 비개발자에게 설명한 경험을 말씀해 주세요.",
        "ideal_answer": "청중의 배경 파악 → 핵심 인사이트 1가지로 압축 → 시각화(차트 유형 선택 이유) → 비즈니스 언어로 번역(매출/비용/리스크) → 다음 행동 제안 포함.",
        "keywords": ["커뮤니케이션", "시각화", "대시보드", "비기술"],
        "quality_score": 1.0,
    },
    {
        "role_key": "데이터 분석가",
        "company_name": None,
        "category": "competency",
        "question": "데이터 품질 문제를 발견하고 해결한 경험을 말씀해 주세요.",
        "ideal_answer": "이상치/결측치 탐지 방법 → 원인 추적(수집/파이프라인/소스) → 데이터 오너와 협업 → 검증 자동화(데이터 계약/모니터링) → 신뢰도 지표 개선.",
        "keywords": ["데이터 품질", "이상치", "파이프라인", "검증"],
        "quality_score": 1.0,
    },
    # ── 인사(HR) ──
    {
        "role_key": "인사(HR)",
        "company_name": None,
        "category": "competency",
        "question": "채용 프로세스를 개선한 경험이 있으신가요?",
        "ideal_answer": "기존 프로세스의 문제(리드타임 길다/후보자 이탈) → 원인 분석 → 개선 조치(서류 기준 명확화/면접관 교육/ATS 도입) → 결과(합격률·만족도 수치). 후보자 경험 관점 포함.",
        "keywords": ["채용", "HR", "프로세스", "인재"],
        "quality_score": 1.0,
    },
]
